"""empty message

Revision ID: 647d1780bae9
Revises: 39d02210cb0b
Create Date: 2022-09-19 10:55:11.530320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647d1780bae9'
down_revision = '39d02210cb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cloudinary_id', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'product', ['cloudinary_id'])
    op.create_unique_constraint(None, 'product', ['name'])
    op.create_unique_constraint(None, 'product', ['img_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'cloudinary_id')
    # ### end Alembic commands ###
